version: "3"

services:
  catalog_service:
    build:
      context: ./catalog
    ports:
      - "5000:5000"
    volumes:
      - ./catalog:/app
    command: python catalog.py

  order_service:
    build:
      context: ./order
    ports:
      - "6000:6000"
    volumes:
      - ./order:/app
    command: python order.py

  gateway_service:
    build:
      context: ./gateway
    ports:
      - "5050:5050"
    volumes:
      - ./gateway:/app
    command: python gateway.py

  frontend_service:
    build:
      context: ./frontend
    ports:
      - "6050:6050"
    volumes:
      - ./frontend:/app
    command: python frontend.py
